uwaterlooacs/acs

package.json, yarn.lock
I got rid of the `run` command in the scripts since it isn't necessary and for consistency, since it wasn't used for `yarn start` in the `dev` script. Not that it matters :D
=> Fix ESLint Setup + Build Script Update

.eslintrc.json, client/src/components/forms/Login/index.tsx, client/src/components/forms/SignUp/index.tsx, client/src/context/theme/provider.tsx, src/models/user.ts
Added some rules about bracket, paren and brace spacing
=> [eslint] Updated eslint rules and ran fix

client/.storybook/main.js, client/package.json, client/src/components/forms/MailingList/index.stories.js, client/src/components/forms/MailingList/index.tsx, client/yarn.lock
Stories files should be `.js` because we don't want to worry about typing or linting these files
=> [easy] Storybook init

client/package.json, client/src/components/forms/MailingList/events.ts, client/src/components/forms/MailingList/index.stories.js, client/src/components/forms/MailingList/index.tsx, client/src/components/forms/MailingList/slides/Email.tsx, client/src/components/forms/MailingList/slides/Feedback.tsx, client/src/components/forms/MailingList/slides/Social.tsx, client/src/components/forms/MailingList/types.ts, client/src/pages/Home/index.tsx, client/yarn.lock
1. Created static events based on Danicia's list
2. Cleaned up and made code a little more robust
> Removed some unnecessary style classes
> Created array for slides
3. Added email validation 
I say we try a deploy of the UI and test em
=> [big boy][UI] Mailing list

client/src/components/forms/MailingList/index.tsx, client/src/components/forms/MailingList/slides/Feedback.tsx, client/src/types/mailingList.ts, client/src/utils/data/mailingList.ts, client/src/utils/network/endpoints.ts, client/src/utils/network/errorMessages.ts
[🔌](https://docs.google.com/spreadsheets/d/16PEbh4LFsb1klDX-W6kp47_p9acEKVIWNBz-TTDXcDc/edit#gid=0)
=> [smol] Hook up mailing list response submission

client/src/components/forms/MailingList/index.tsx, client/src/components/forms/MailingList/slides/Feedback.tsx
Removed slides array because the values are fixed and we didn't need it
Loading indicator for submit button
```
UI
```
=> [easy] Cleanup + loading indicator

client/src/components/forms/MailingList/events.ts, client/src/components/forms/MailingList/slides/Email.tsx
=> text changes

app.ts, src/routers/user/index.ts
I moved this boy to `app.ts` since we only need to import it once and all routes that use the DB benefit from it.
=> [one liner] Move mongoose setup file import

app.ts, package.json, src/jobs/membership.ts, src/models/user.ts, yarn.lock
Added cron job to 
1. store member info in a google sheet
2. reset membership list
Here's how I derived the cron expression: https://crontab.guru/#0_0_1_JAN,MAY,SEP_*
We're running this job once on the 1st of Jan, May, Sept
We just set everyone's membership in the db to `EXPIRED`. Here's a sc of 2 users' membership status after the script was run
One was paid and the other was unpaid
Adds a new sheet to the Google Spreadsheet Doc for each term (each time the script runs) and then exports members to that sheet.
Did some manual tests and the job works okay.
=> Reset membership

client/src/pages/Membership/index.tsx
I messed up a fixing a merge conflict and accidentally re-added the `AuthPanel` on the membership page.
my b
=> [messed up] Fix bad merge

client/src/components/forms/SignUp/SignUp.stories.tsx, client/src/components/forms/SignUp/index.tsx, client/src/utils/constants.ts
Updated the `SignUp` form component to match Josh's designs.
The form doesn't actual do anything yet. This PR contains the UI elements with no state or submission logic.
=> [UI only] Add SignUp form UI

client/src/components/SignUp/index.tsx, client/src/components/lists/Users/index.tsx, client/src/context/user/state.ts, client/src/types/user.ts, client/src/utils/data/user.ts, src/jobs/membership.ts, src/models/user.ts, src/routers/user/routeValidator.ts, src/types/user.ts, src/utils/customValidators.ts
Did a lot of stuff to get the backend and frontend in sync and ready to handle and send requests.
The size of the PR kinda got away from me. It started tiny but I kept adding things. my b!
- Added student number to the `UserModel` and added validation for it in `/user/signup` route handler 🔢 
- Replaced `name` with `firstName` and `lastName`.
- Bring client `User` and `UserData` types up to date with backend.
- Add `SignUpUserData` to use to type signup request data.
- Add semester and faculty to `UserModel`
Also fixed small issue with `isPassword` where it would throw unexpectedly if `password` is undefined. It throws expectedly now.
=> [signup p6] UserModel changes (name → firstName, lastName; add studentNumber)

client/src/components/SignUp/index.tsx, client/src/components/forms/SignUp/constants.ts, client/src/components/forms/SignUp/index.tsx, client/src/components/forms/SignUp/utils.ts, client/src/components/lists/Users/index.tsx, client/src/context/user/state.ts, client/src/types/user.ts, client/src/utils/data/user.ts, src/jobs/membership.ts, src/models/user.ts, src/routers/user/routeValidator.ts, src/types/user.ts, src/utils/customValidators.ts
Added validation to `SignUpForm`.
We can tweak the validation for first name and last name. Right now it's `length > 0` and only contains alphabetic characters, spaces and dashes.
=> [signup p5] Add SignUpForm validation

README.md
I had to add this env var to get it working recently so I'll drop it in the docs one time ⬇️
=> Add environmental variables section to README

client/src/components/lists/MembershipOption/option.tsx
Refined UI
1. Fixed width for an option
2. Shows description on mobile
3. Transition from bottom to top
desktop
mobile
Do transition for arrow
=> Membership Options 3

client/src/components/Benefits/Row.tsx, client/src/components/Benefits/benefits.ts, client/src/components/Benefits/index.stories.tsx, client/src/components/Benefits/index.tsx, client/src/components/Benefits/types.ts
This PR should be super light to review. Nothing too fancy / crazy.
Added UI fro Member Benefits
I haven't put this together with the sign up form, but maybe we should take another look at the `integration` tasks since we're done individual sections?
Lmk how u wanna put this all together. I can help out if you want😅
=> [easy] Member Benefits

client/src/components/ShrinkImage/index.tsx, client/src/components/forms/SignUp/index.tsx, client/src/pages/MailingList/index.stories.tsx
Cleaned up some of the `eslint` and `prettier` issues in our codebase
Merging for now. Can revert later if necessary
=> [easy] Cleanup

client/src/components/VerifyInfo/index.stories.tsx, client/src/components/VerifyInfo/index.tsx
Added the component that has verify your information.
Right now the default values on the form are set from the user in context. 
The user can modify these values using the form.
When they click submit, the validation from utils is run (`isName`, `isUWEmail`...)
If everything is good, it sets these updated values to the user in context.
from storybook
Next I'll be creating this
And then I'll put things together🤙
=> Verify Info PART 2

README.md
The `README.md` includes instructions to update the file permission of the downloaded key file `acs-website.pem`
=> Add line on updating key file permissions

packages/server/src/routers/nomination/index.ts, packages/server/src/routers/nomination/types.ts, packages/server/src/routers/nomination/validations.ts
=> added vote route

packages/client/src/components/NomineeCard/NomineeCard.stories.tsx, packages/client/src/components/NomineeCard/index.tsx
=> Add initial NomineeCard

packages/server/src/routers/voting/index.ts
=> Get Stage Route

packages/server/src/routers/nomination/index.ts, packages/server/src/routers/nomination/types.ts, packages/server/src/routers/voting/utils.ts
Made a route to call helper function
=> Get Nominations By Position
