uwaterlooacs/acs

client/src/App.tsx
client/src/context/user/actions.ts
client/src/context/user/provider.tsx
client/src/context/user/reducer.ts
client/src/context/user/state.ts
client/src/types/user.ts

After user authenticates, we want to store their info as well as their auth token (generated by the server) in context so that it's accessible throughout the client app.
This PR introduces actions, a reducer and a provider that allow this to happen.
I also realized that the user type needed a slight tweak. 
After the user authenticates, we don't want to keep track of their secret for security reasons.
(A user's secret is their password or something private if they use a 3p auth service like Facebook / Google)
Any time the server returns a user it deletes the secret KVP from the doc (so secret should be optional on a `User`).
However we do want the `Credentials` type to have both email and secret.

[infra] User Context

---

client/src/utils/network/request.ts

I was just glossing over some code that was written to communicate with the backend and I noticed that some logic could be simplified.
In production, the client can resolve all api routes through itself (because the server serves the client)
However, for development we need to specify port 5000.
The param `urlExt` should be something like `/api/mailingList` or something like that.
There are some examples in the `client/src/utils/data` folder

[smol] Refactored makeRequest

---

README.md
scripts/deploy.sh

Added a little script that can be run from inside the ec2 instance to deploy the latest remote code. Also added some documentation on how to deploy using the script.
Once this is merged I'll go in and `chmod +x ./scripts/deploy.sh` so that it's executable.
- Only works when run from inside ec2 instance
- Warns when deploying a branch other than master
- Has some nice colors

[📜 + 📝] EC2 deployment script + Documentation

---

package.json
src/models/user.ts
src/routers/mailingList/validator.ts
src/routers/user/index.ts
src/routers/user/routeValidator.ts
src/routers/user/types.ts
yarn.lock

I added this route but I realize we don't have designs for what happens when the user checks their membership. Presumably, the user is told that they are an active member, inactive member or not a member (and maybe whether or not they have paid?) and directed to press a button to go to log in, renew membership or sign up.
For now, I'm just returning the whole user object but we'll definitely want to change that in the future. I added the `watIAMUserId` field to the user model but didn't tackle adding anything to track membership status.
How do you see us tracking membership status?
Do we want to have a history of whether a user was active for previous terms or only the current term?

[~1 hunnit] Add user membership check API route

---

client/src/components/forms/Login/index.tsx
client/src/components/forms/SignUp/index.tsx
client/src/types/user.ts
src/models/user.ts
src/routers/user/index.ts

I think the only reason why I used the name secret was because user's who authenticate with a 3rd party like FB / Google didn't have passwords, but I think for the time being, we're only going to support authentication with emails and passwords. 
I don't think this is likely to change in the future because we want ppl to use their school emails
You'll probably want to drop your db if you have any old test users in there

[easy] Renamed secret to password

---

src/routers/mailingList/index.ts
src/routers/mailingList/routeValidator.ts

I think `routeValidator` is a better name anyways.

[tiny] Rename route validator to avoid clash with validator package

---

src/models/user.ts
src/types/user.ts

I think we should have 3 membership types and store the current type on the user. 
If that sounds good, I'll also write a cron job to set all current members' membership status to `EXPIRED` at the end of a term.
What do you think?

[small][up 4 discussion] Proposed membership types

---

src/routers/user/index.ts

`/api/user/membership-check` will only return user's `membershipStatus` (along with id in object) instead of all user fields.
Cool PR template

Use projection to only return membershipStatus

---

src/routers/user/index.ts
src/routers/user/routeValidator.ts
src/routers/user/types.ts
src/utils/customValidators.ts

On `/api/user/signup` route:
- Set `membershipStatus` based on `paid` field in request body
- Validate request body
We lost the `M.SIGN_UP` error message since I'm sending whatever errors arise to the default error handler. Maybe we can send the error as an object with an error property that would contain the originally thrown error and then we can set the message as `M.SIGN_UP`. Then we have less control to send a specific message instead of the generic one when trying to throw from inside the catch block tho.
What do you think?

Update /api/user/signup route

---

src/middleware/auth.ts
src/models/user.ts
src/routers/user/index.ts
src/routers/user/membership.ts
src/routers/user/routeValidator.ts
src/routers/user/types.ts
src/types/network.ts

2 things have actually changed in this PR
1. I added a route for setting the membership status of a user
```
type: PATCH
body: { membershipStatus: MEMBERSHIP_STATUS }
query: { id: ObjectId } // id represents the user's id whose membership status you want to update 
```
2. I migrated the membership status check route from the `routes/user/index.ts` to `routes/user/membership.ts` and made the following slight modifications (which are open 4 discussion)
* route is now `/api/user/membership/check` instead of `/api/user/membership-check` because we have more membership routes
* I changed the type of the request from `POST` to `GET`
I think that would be the better type of request since we're requesting info on a doc (see [this W3 article](https://www.w3schools.com/tags/ref_httpmethods.asp) for …

Updated membership routes

---

client/src/components/SignUp/index.tsx
client/src/components/lists/Users/index.tsx
client/src/context/user/state.ts
client/src/types/user.ts
client/src/utils/data/user.ts

The `SignUp` component will now actually sign up the user from the `CreateAccountForm` by sending a request with the info to the backend.
The component is basically complete now except for a failed signup state. It just needs to be dropped into a `JoinACS` or other name component and displayed after the signup button on the Membership page is pressed¡

[signup p7] Signup request

---

client/src/components/SignUp/index.tsx
client/src/components/forms/CreateAccount/constants.ts
client/src/components/forms/CreateAccount/index.tsx
client/src/components/forms/CreateAccount/utils.ts
client/src/components/forms/SignUp/constants.ts
client/src/components/forms/SignUp/index.tsx
client/src/components/forms/SignUp/utils.ts
client/src/components/lists/Users/index.tsx
client/src/context/user/state.ts
client/src/types/user.ts
client/src/utils/data/user.ts
src/jobs/membership.ts
src/models/user.ts
src/routers/user/routeValidator.ts
src/types/user.ts
src/utils/customValidators.ts

Added some validation to the `CreateAccountForm`. It will now only call `onNext` if its validation passes. Validation includes:
1. Password is valid (at least 8 characters)
2. Password and re-entered password matches
I had to copy and modify the `isPassword` util from the server-side since we don't have a great way to share code between them.

[signup p4] Create account validation

---

client/src/components/SignUp/SignUp.stories.tsx
client/src/components/SignUp/index.tsx
client/src/components/forms/CreateAccount/CreateAccount.stories.tsx
client/src/components/forms/CreateAccount/constants.ts
client/src/components/forms/CreateAccount/index.tsx
client/src/components/forms/CreateAccount/utils.ts
client/src/components/forms/SignUp/SignUp.stories.tsx
client/src/components/forms/SignUp/constants.ts
client/src/components/forms/SignUp/index.tsx
client/src/components/forms/SignUp/utils.ts
client/src/components/lists/Users/index.tsx
client/src/context/user/state.ts
client/src/types/user.ts
client/src/utils/data/user.ts
src/jobs/membership.ts
src/models/user.ts
src/routers/user/routeValidator.ts
src/types/user.ts
src/utils/customValidators.ts

Added the `SignUp` component. Not to be confused with the previous `SignUp` component in the `components/forms` directory which is now renamed to `SignUpForm`.
This is a hefty boy. It's mostly just refactors to make the two form components controlled.
- Makes `CreateAccountForm` and `SignUpForm` components controlled in that they take their values and setters from props.
- Validation will be done in each component and will only call `onNext` if validation passes.

[signup p3][⚓] Signup component

---

client/src/components/lists/MembershipOption/index.tsx
client/src/components/lists/MembershipOption/option.tsx
client/src/pages/Membership/index.tsx

First I moved some of the auth panel opening logic out of the `Option` component and into the `OptionList` component. Then I added the `history.push` to change the route on "SIGN UP" option clicked.
I added a switch and routes for `HowToJoin` and for the root membership page that we already had 🥳  I'll add the last one for sign up (`/membership/signup`).
I also added a lil fade animation furda 😁

Add HowToJoin Page on /howtojoin route

---

client/src/components/forms/SignUp/index.tsx
client/src/pages/Membership/HowToJoin/index.tsx
client/src/pages/Membership/SignUp/index.tsx
client/src/pages/Membership/index.tsx

Added da `SignUpPage`
I had to add a key to the Fade component to get it to work properly. I think React was confusing it for the other `Fade` component from `/howtojoin` and not unmounting in remounting it on navigation. Not sure but the key prop fix works.

Add SignUpPage on /membership/signup route

---

scripts/deploy.sh

The deploy script no longer compares `"branch"` to `"master"` to determine if we're on the master branch ! 😀 
No change
Use the variable value itself and not the string literal for comparisons 👍

[ez] Fix non-master branch alert in deploy script

---

client/src/components/ShrinkImage/index.tsx

The `ShrinkImage` works in production builds  🎉 
`prodUI === localUI`
Super weird bug that took way to long to figure out 😅 Not sure exactly why wrapping the return of the child render function works or why I can't find anything about it online but maybe we just wrap all our returns like that in single `div`s.
Related to [this trello item](https://trello.com/c/5je62pet/52-shrinkimage-doesnt-show-up-in-production)

[fix][ez] Add a wrapper around img in ShrinkImage

---

client/src/components/lists/MembershipOption/option.tsx

MembershipOptions are displayed either horizontally or vertically depending on screen size.
Now on tablets they are displayed vertically.

[ez][fix] Use smaller horizontal size for Membership Options on desktop up

---

client/src/components/AuthPanel/index.tsx
client/src/components/SignUp/index.tsx
client/src/components/VerifyInfo/index.stories.tsx
client/src/components/VerifyInfo/index.tsx
client/src/pages/Membership/VerifyInfo/index.tsx
client/src/pages/Membership/index.tsx

Completed the renew membership flow
Desktop
Mobile
Looks good on tablet too😂 I checked
I'll work on backend integration sometime. 
But we should work on edge cases.
E.g. if a user tries to sign up but their email / student id is already in use.
same thing with membership renewal
Need to start handling those from UI side

Renew Membership Flow

---

src/middleware/auth.ts
src/models/voting.ts
src/routers/api.ts
src/routers/user/index.ts
src/routers/user/membership.ts
src/routers/voting/index.ts
src/routers/voting/routeValidator.ts
src/types/voting.ts
src/utils/constants.ts
src/utils/enum.ts

We now have a VotingModel with the static `getVotingDoc` method which should always be used instead of `.find()`, `.findOne()`, etc since it only contains one document with global voting data (right now only the voting `stage`).
I also added the PATCH `/api/voting/stage` route for admins to update the stage.
The auth middleware function now takes `AuthOptions` and returns the middleware with those options set. This is useful for customizing the middleware. Now we can do `auth({ isAdmin: true })` to require that the user is authenticated and an admin.
I refactored all the code using `auth` as middleware to `auth()`. 
- Not a huge fan of this method of creating a whole table to store one doc but it works!
- Not sure if you're planning on nesting the `/nominations` routes in voting but we …

VotingModel and update voting stage route

---

client/src/components/AuthPanel/index.tsx
client/src/components/VerifyInfo/index.tsx
client/src/types/user.ts
client/src/utils/api/endpoints.ts
client/src/utils/api/membership.ts
src/routers/user/membership.ts
src/types/user.ts

Integrated the backend for Renew Membership and Membership Check. Decided to merge these 2 cause check was smol.
If the user isn't logged in when they try to renew their membership, the panel changes to the `login` panel and they're prompted to log in.
If the user is logged in when they try to renew their membership, we try setting their membership status to `unpaid` (unless they're already a full member).
If they're successful, then we allow them to update their info. If they're not, then something went wrong on the server side so then they stay on the membership page and see a ☹️ message. 
Pretty explanatory. The user can use either their watiam or email.
Renew flow
Check
Anything additional that reviewers should know going about your changes / going forward

Renew Membership + Membership Check

---

client/src/components/AuthPanel/index.tsx
client/src/components/Header/Menu.tsx
client/src/components/VerifyInfo/index.tsx
client/src/components/lists/MembershipOption/index.tsx
client/src/context/user/state.ts
client/src/types/user.ts
client/src/utils/api/endpoints.ts
client/src/utils/api/membership.ts
src/routers/user/membership.ts
src/types/user.ts

Not sure if you noticed in https://github.com/uwaterlooacs/acs/pull/74 but when the user authenticates, we don't want them to see log in / sign up buttons. This PR hides those buttons from the header and from the membership page.
Refer to https://github.com/uwaterlooacs/acs/pull/74

Authenticated Renders

---

src/data/positions.ts
src/routers/api.ts
src/routers/dev/index.ts
src/routers/nomination/index.ts
src/routers/nomination/types.ts
src/routers/nomination/validations.ts
src/utils/constants.ts

In this PR, we add the route to create nominations.
However, to create a nomination, you need positions to exist first. So I created a `devRoute` for populating the db with positions (if they don't already exist). We can consider this like a startup script for developers of this repo because we will need that test data to do any voting testing and this makes it a bit easier. We can secure this with a authentication using a dev token so that only we can hit it (will ticket for future implementation).
So after we have all the positions, we can create nominations. There is a new router and validations for it.
Also let me know what you think about this convention for validators:
1. In each router folder, we can create an enum called `LocalRoutes` and give a description of the route that we …

[misleadingly big] Create Nominations

---

src/models/nomination.ts
src/routers/nomination/index.ts
src/routers/nomination/types.ts
src/routers/nomination/validations.ts

1. Updated the create nomination route to disallow duplicate nominations.
2. Created a route for seconding a nominee.
```
PATCH .../nomination/second?candidate={id}&position={id}
```
We pass a candidate id and a position id to find the nomination. Once we have the nomination, we can second it by adding our user id to the list of seconds. If we've already seconded the nomination before, then we get back an error.
Danicia is asking on status updates so I feel like we should try to get some more progress on voting.

Seconding a nominee

---

.circleci/config.yml
packages/server/package.json
packages/shared/package.json

We now just call `tsc` instead of `node ../../node_modules/blahblah/tsc`
⭕️ builds

Updated ⭕️ build scripts

---

packages/server/src/models/nomination.ts
packages/server/src/routers/voting/index.ts
packages/server/src/routers/voting/utils.ts
packages/shared/src/models/nomination.ts

Update the PositionDocs with new occupant and `isOpen = false` when the voting stage is updated through PATCH at `/voting/stage` from the vote stage to the results stage.

Finalize position winners when voting is complete
